// desk-helper — Digital Desk's native companion process.
//
// Protocol: JSON lines. Requests arrive on stdin ({"id":1,"cmd":"…"}), responses and
// events go to stdout. See docs/ARCHITECTURE.md §5. The process exits when stdin closes,
// so it never outlives the app.

import AppKit
import Foundation
import Vision

let protocolVersion = 1
let pollInterval: TimeInterval = 0.25

// MARK: - Output

let outputQueue = DispatchQueue(label: "desk-helper.stdout")

func emit(_ object: [String: Any]) {
    guard JSONSerialization.isValidJSONObject(object),
          var data = try? JSONSerialization.data(withJSONObject: object, options: [])
    else { return }
    data.append(0x0A)
    outputQueue.sync { FileHandle.standardOutput.write(data) }
}

// MARK: - Frontmost app

func frontmostApp() -> [String: Any] {
    guard let app = NSWorkspace.shared.frontmostApplication else { return [:] }
    var info: [String: Any] = ["pid": Int(app.processIdentifier)]
    if let name = app.localizedName { info["name"] = name }
    if let bundleId = app.bundleIdentifier { info["bundleId"] = bundleId }
    return info
}

// MARK: - Pasteboard

// Markers apps use to say "don't record this" (http://nspasteboard.org).
let concealedTypes: Set<String> = [
    "org.nspasteboard.ConcealedType",
    "com.agilebits.onepassword",
]
let transientTypes: Set<String> = [
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
]

final class PasteboardWatcher {
    private let pasteboard = NSPasteboard.general
    private(set) var lastChangeCount: Int

    init() {
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        let timer = Timer(timeInterval: pollInterval, repeats: true) { [weak self] _ in self?.poll() }
        timer.tolerance = 0.05
        RunLoop.main.add(timer, forMode: .common)
    }

    private func poll() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        // Reading type names only — never contents. The app decides whether to read.
        let types = (pasteboard.types ?? []).map(\.rawValue)
        let typeSet = Set(types)
        emit([
            "event": "pasteboard",
            "changeCount": count,
            "app": frontmostApp(),
            "types": types,
            "concealed": !typeSet.isDisjoint(with: concealedTypes),
            "transient": !typeSet.isDisjoint(with: transientTypes),
            "at": Int(Date().timeIntervalSince1970 * 1000),
        ])
    }

    /// Puts files on the pasteboard the way Finder's Copy does. Returns the new change count.
    func writeFiles(_ paths: [String]) -> Int {
        pasteboard.clearContents()
        pasteboard.writeObjects(paths.map { URL(fileURLWithPath: $0) as NSURL })
        return pasteboard.changeCount
    }

    func fileURLs() -> [String] {
        let options: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
        let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: options) as? [URL] ?? []
        return urls.map(\.path)
    }
}

// MARK: - Files: Spotlight-style metadata, screenshot folder, OCR

/// Reads a `com.apple.metadata:*` extended attribute (a binary plist). Written immediately by
/// screencapture and browsers, so it beats waiting for Spotlight to index the file.
func metadataAttribute(_ path: String, _ name: String) -> Any? {
    let attr = "com.apple.metadata:\(name)"
    let size = getxattr(path, attr, nil, 0, 0, 0)
    guard size > 0 else { return nil }
    var data = Data(count: size)
    let read = data.withUnsafeMutableBytes { getxattr(path, attr, $0.baseAddress, size, 0, 0) }
    guard read == size else { return nil }
    return try? PropertyListSerialization.propertyList(from: data, options: [], format: nil)
}

func fileMetadata(_ path: String) -> [String: Any] {
    var isScreenCapture = (metadataAttribute(path, "kMDItemIsScreenCapture") as? Bool) ?? false
    var whereFroms = (metadataAttribute(path, "kMDItemWhereFroms") as? [String]) ?? []
    if let item = MDItemCreate(nil, path as CFString) {
        // kMDItemIsScreenCapture has no Swift constant; the attribute name is stable.
        if !isScreenCapture, let value = MDItemCopyAttribute(item, "kMDItemIsScreenCapture" as CFString) as? Bool {
            isScreenCapture = value
        }
        if whereFroms.isEmpty, let value = MDItemCopyAttribute(item, kMDItemWhereFroms) as? [String] {
            whereFroms = value
        }
    }
    return ["isScreenCapture": isScreenCapture, "whereFroms": whereFroms]
}

func screenshotLocation() -> String {
    let configured = UserDefaults(suiteName: "com.apple.screencapture")?.string(forKey: "location")
    let path = (configured?.isEmpty == false ? configured! : "~/Desktop") as NSString
    return path.expandingTildeInPath
}

let ocrQueue = DispatchQueue(label: "desk-helper.ocr", qos: .utility)

/// On-device text recognition, Korean + English (ARCHITECTURE §5). Lines come top to bottom.
func recognizeText(_ path: String) throws -> [[String: Any]] {
    guard let image = NSImage(contentsOfFile: path),
          let cgImage = image.cgImage(forProposedRect: nil, context: nil, hints: nil)
    else { throw NSError(domain: "desk-helper", code: 1, userInfo: [NSLocalizedDescriptionKey: "cannot read image"]) }
    let request = VNRecognizeTextRequest()
    request.recognitionLevel = .accurate
    request.recognitionLanguages = ["ko-KR", "en-US"]
    request.usesLanguageCorrection = true
    return try recognize(cgImage, request)
}

func recognize(_ cgImage: CGImage, _ request: VNRecognizeTextRequest) throws -> [[String: Any]] {
    try VNImageRequestHandler(cgImage: cgImage, options: [:]).perform([request])
    let observations = (request.results ?? []).sorted { $0.boundingBox.maxY > $1.boundingBox.maxY }
    return observations.compactMap { obs in
        guard let top = obs.topCandidates(1).first else { return nil }
        return ["text": top.string, "confidence": Double(top.confidence)]
    }
}

/// The first recognition in a newly installed binary takes ~25 s while the system prepares the
/// models (measured on macOS 27); later ones take ~0.6 s, across restarts too. Pay that once at
/// launch in the background instead of on the user's first screenshot.
func warmUpOCR() {
    ocrQueue.async {
        let width = 320, height = 80
        guard let ctx = CGContext(data: nil, width: width, height: height, bitsPerComponent: 8, bytesPerRow: 0,
                                  space: CGColorSpaceCreateDeviceGray(), bitmapInfo: CGImageAlphaInfo.none.rawValue)
        else { return }
        ctx.setFillColor(gray: 1, alpha: 1)
        ctx.fill(CGRect(x: 0, y: 0, width: width, height: height))
        ctx.setFillColor(gray: 0, alpha: 1)
        ctx.fill(CGRect(x: 20, y: 30, width: 280, height: 20))
        guard let image = ctx.makeImage() else { return }
        let request = VNRecognizeTextRequest()
        request.recognitionLevel = .accurate
        request.recognitionLanguages = ["ko-KR", "en-US"]
        request.usesLanguageCorrection = true
        let started = Date()
        _ = try? recognize(image, request)
        emit(["event": "ocrReady", "ms": Int(Date().timeIntervalSince(started) * 1000)])
    }
}

// MARK: - Requests

let watcher = PasteboardWatcher()

func handle(_ request: [String: Any]) {
    let id = request["id"] ?? NSNull()
    let cmd = request["cmd"] as? String ?? ""
    switch cmd {
    case "ping":
        emit(["id": id, "ok": true, "version": protocolVersion])
    case "frontmost":
        emit(["id": id, "ok": true, "app": frontmostApp()])
    case "writeFiles":
        let paths = (request["paths"] as? [String] ?? []).filter { FileManager.default.fileExists(atPath: $0) }
        guard !paths.isEmpty else {
            emit(["id": id, "ok": false, "error": "no existing files"])
            return
        }
        emit(["id": id, "ok": true, "changeCount": watcher.writeFiles(paths)])
    case "mdmeta":
        guard let path = request["path"] as? String else {
            emit(["id": id, "ok": false, "error": "path required"])
            return
        }
        emit(["id": id, "ok": true].merging(fileMetadata(path)) { a, _ in a })
    case "screenshotLocation":
        emit(["id": id, "ok": true, "path": screenshotLocation()])
    case "ocr":
        guard let path = request["path"] as? String else {
            emit(["id": id, "ok": false, "error": "path required"])
            return
        }
        // Off the main thread so pasteboard polling keeps running.
        ocrQueue.async {
            let started = Date()
            do {
                let lines = try recognizeText(path)
                emit(["id": id, "ok": true, "lines": lines, "ms": Int(Date().timeIntervalSince(started) * 1000)])
            } catch {
                emit(["id": id, "ok": false, "error": error.localizedDescription])
            }
        }
    case "pasteboardFiles":
        emit(["id": id, "ok": true, "paths": watcher.fileURLs(), "changeCount": watcher.lastChangeCount])
    default:
        emit(["id": id, "ok": false, "error": "unknown command: \(cmd)"])
    }
}

func readRequests() {
    while let line = readLine(strippingNewline: true) {
        guard !line.isEmpty,
              let data = line.data(using: .utf8),
              let object = try? JSONSerialization.jsonObject(with: data) as? [String: Any]
        else {
            emit(["ok": false, "error": "invalid request"])
            continue
        }
        // AppKit objects are touched on the main thread only.
        DispatchQueue.main.async { handle(object) }
    }
    // stdin closed: the app is gone.
    exit(0)
}

// MARK: - Main

signal(SIGPIPE, SIG_IGN)
let app = NSApplication.shared
app.setActivationPolicy(.prohibited)

watcher.start()
warmUpOCR()
Thread.detachNewThread(readRequests)
emit(["event": "ready", "version": protocolVersion, "changeCount": watcher.lastChangeCount, "pid": Int(getpid())])

app.run()
